// Mock database for demo mode
const mockData = {
  users: [
    {
      _id: '1',
      email: 'admin@demo.com',
      password: '$2a$10$YourHashedPassword123456789012345', // demo123 hashed
      name: 'Admin User',
      role: 'admin',
      restaurantId: '1',
      phone: '9876543210',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '2',
      email: 'superadmin@aapkirasoi.com',
      password: '$2a$10$YourHashedPassword123456789012345', // demo123 hashed
      name: 'Super Admin',
      role: 'superadmin',
      phone: '9999999999',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  restaurants: [
    {
      _id: '1',
      name: 'Aapki Rasoi - Downtown',
      address: '123 Food Street, City Center',
      phone: '9876543210',
      email: 'contact@aapkirasoi.com',
      logo: 'https://via.placeholder.com/100',
      taxRate: 18,
      currency: '₹',
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  menuCategories: [
    {
      _id: '1',
      restaurantId: '1',
      name: 'Indian Curries',
      description: 'Delicious Indian curry dishes',
      order: 1,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '2',
      restaurantId: '1',
      name: 'Breads',
      description: 'Fresh baked breads',
      order: 2,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '3',
      restaurantId: '1',
      name: 'Beverages',
      description: 'Drinks and beverages',
      order: 3,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  menuItems: [
    {
      _id: '1',
      restaurantId: '1',
      categoryId: '1',
      name: 'Butter Chicken',
      description: 'Creamy butter chicken curry',
      price: 350,
      image: 'https://via.placeholder.com/200',
      isAvailable: true,
      preparationTime: 20,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '2',
      restaurantId: '1',
      categoryId: '1',
      name: 'Paneer Tikka Masala',
      description: 'Cottage cheese in creamy tomato sauce',
      price: 320,
      image: 'https://via.placeholder.com/200',
      isAvailable: true,
      preparationTime: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '3',
      restaurantId: '1',
      categoryId: '2',
      name: 'Naan',
      description: 'Traditional Indian bread',
      price: 60,
      image: 'https://via.placeholder.com/200',
      isAvailable: true,
      preparationTime: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '4',
      restaurantId: '1',
      categoryId: '3',
      name: 'Masala Chai',
      description: 'Indian spiced tea',
      price: 80,
      image: 'https://via.placeholder.com/200',
      isAvailable: true,
      preparationTime: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  orders: [
    {
      _id: '1',
      restaurantId: '1',
      orderType: 'dine_in',
      status: 'delivered',
      items: [
        {
          menuItemId: '1',
          name: 'Butter Chicken',
          quantity: 2,
          price: 350,
          total: 700,
        },
        {
          menuItemId: '3',
          name: 'Naan',
          quantity: 2,
          price: 60,
          total: 120,
        },
      ],
      subtotal: 820,
      tax: 147.6,
      taxRate: 18,
      discount: 0,
      discountType: 'percentage',
      total: 967.6,
      customerName: 'John Doe',
      customerPhone: '9876543210',
      tableNumber: '5',
      paymentMethod: 'cash',
      paymentStatus: 'paid',
      notes: 'Sample order',
      createdAt: new Date(Date.now() - 86400000),
      updatedAt: new Date(Date.now() - 86400000),
    },
  ],
  bills: [
    {
      _id: '1',
      restaurantId: '1',
      orderId: '1',
      billNumber: 'BILL-000001',
      items: [
        {
          menuItemId: '1',
          name: 'Butter Chicken',
          quantity: 2,
          price: 350,
          total: 700,
        },
        {
          menuItemId: '3',
          name: 'Naan',
          quantity: 2,
          price: 60,
          total: 120,
        },
      ],
      subtotal: 820,
      tax: 147.6,
      taxRate: 18,
      discount: 0,
      discountType: 'percentage',
      total: 967.6,
      paymentMethod: 'cash',
      paymentStatus: 'paid',
      customerName: 'John Doe',
      tableNumber: '5',
      createdAt: new Date(Date.now() - 86400000),
      updatedAt: new Date(Date.now() - 86400000),
    },
  ],
  inventory: [
    {
      _id: '1',
      restaurantId: '1',
      name: 'Onions',
      quantity: 50,
      unit: 'kg',
      alertThreshold: 10,
      category: 'vegetables',
      purchasePrice: 30,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '2',
      restaurantId: '1',
      name: 'Tomatoes',
      quantity: 5,
      unit: 'kg',
      alertThreshold: 15,
      category: 'vegetables',
      purchasePrice: 40,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      _id: '3',
      restaurantId: '1',
      name: 'Chicken',
      quantity: 8,
      unit: 'kg',
      alertThreshold: 10,
      category: 'meat',
      purchasePrice: 200,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};

module.exports = mockData;
